server:
  port: 8080

spring:
  application:
    name: api-gateway

spring:
  cloud:
    gateway:
      routes:
        - id: employer-service
          uri: lb://employer-service
          predicates:
            - Path=/api/employers/**
          filters:
            - StripPrefix=1

        - id: jobopening-service
          uri: lb://jobopening-service
          predicates:
            - Path=/api/job-openings/**
          filters:
            - StripPrefix=1

        - id: jobseeker-service
          uri: lb://jobseeker-service
          predicates:
            - Path=/api/jobseekers/**
          filters:
            - StripPrefix=1

        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/api/applications/**
          filters:
            - StripPrefix=1

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
