server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/dreamjob
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

spring:
  application:
    name: employer-service
